/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/PC.glb 
*/
import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCompContext } from "../contexts/CompContext";

const Case = ({ nodes, materials }) => {
  return (
    <group
      position={[8.485, -0.319, 0.682]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[-0.954, -2.335, -2.19]}
    >
      <mesh geometry={nodes.Object_50.geometry} material={materials["Material.006"]} />
      <mesh geometry={nodes.Object_50_1.geometry} material={materials["Material.058"]} />
      <mesh geometry={nodes.Object_50_2.geometry} material={materials["Material.060"]} />
      <mesh geometry={nodes.Object_50_3.geometry} material={materials["Material.059"]} />
      <mesh geometry={nodes.Object_50_4.geometry} material={materials["Material.003"]} />
      <mesh geometry={nodes.Object_50_5.geometry} material={materials.GamerStorm_logo} />
      <mesh geometry={nodes.Object_50_6.geometry} material={materials["Material.002"]} />
      <mesh geometry={nodes.Object_50_7.geometry} material={materials["Material.036"]} />
      <mesh geometry={nodes.Object_50_8.geometry} material={materials["Material.005"]} />
      <mesh geometry={nodes.Object_50_9.geometry} material={materials["Material.037"]} />
      <mesh geometry={nodes.Object_50_10.geometry} material={materials["Material.004"]} />
      <mesh geometry={nodes.Object_50_11.geometry} material={materials["Material.040"]} />
      <mesh geometry={nodes.Object_50_12.geometry} material={materials["Material.043"]} />
      <mesh geometry={nodes.Object_50_13.geometry} material={materials["Material.038"]} />
      <mesh geometry={nodes.Object_50_14.geometry} material={materials["Material.041"]} />
      <mesh geometry={nodes.Object_50_15.geometry} material={materials["Material.039"]} />
      <mesh geometry={nodes.Object_50_16.geometry} material={materials.material_0} />
    </group>
  );
};

const Sidepanel = ({ nodes, materials, started }) => {
  return (
    <mesh
      geometry={nodes.Object_790.geometry}
      material={materials["Material.003"]}
      position={[7.434, -0.355, 0.672]}
      scale={started ? [0, 0, 0] : [0.008, 1, 1]}
    />
  );
};

const GPUCable = ({ nodes, materials }) => {
  return (
    <mesh
      geometry={nodes.Object_55.geometry}
      material={materials["Material.024"]}
      position={[8.339, -1.407, 0.462]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
    />
  );
};

const HDD = ({ nodes, materials }) => {
  return (
    <mesh
      geometry={nodes.Object_77.geometry}
      material={materials["Material.007"]}
      position={[8.598, -1.958, 1.938]}
      rotation={[Math.PI, 0, Math.PI]}
      scale={[0.889, 0.089, 0.628]}
    />
  );
};

const CPU = ({ nodes, materials, started, setMenuId, controlOpacity, selectedComp, compKey }) => {
  const meshRef = useRef(null);

  useEffect(() => {
    if (started) {
      controlOpacity(meshRef.current.children[0], compKey);
    }
  }, [selectedComp, started]);

  const handlePointerOver = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children[0].children.forEach((c) => {
        c.material.emissive.set("yellow");
        c.material.emissiveIntensity = 0.1;
      });
    }
  };

  const handlePointerOut = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children[0].children.forEach((c, i) => {
        if (i === 1) {
          c.material.emissive.set(16777215);
          c.material.emissiveIntensity = 3.52;
        } else {
          c.material.emissive.set("black");
          c.material.emissiveIntensity = 0;
        }
      });
    }
  };

  const handleClick = (e) => {
    e.stopPropagation();
    setMenuId(compKey);
  };

  return (
    <group
      position={[8.376, 1.913, 0.957]}
      scale={[0.71, 0.077, 0.71]}
      ref={meshRef}
      onPointerOver={started ? handlePointerOver : undefined}
      onPointerOut={started ? handlePointerOut : undefined}
      onClick={started ? handleClick : undefined}
    >
      <group>
        <mesh geometry={nodes.Object_338_5.geometry} material={materials["Material.053"]} />
        <mesh geometry={nodes.Object_338_6.geometry} material={materials["Material.054"]} />
        <mesh geometry={nodes.Object_338_7.geometry} material={materials["Material.042"]} />
        <mesh geometry={nodes.Object_338_4.geometry} material={materials["Material.056"]} />
      </group>
      <group>
        <mesh geometry={nodes.Object_338.geometry} material={materials["Material.051"]} />
        <mesh geometry={nodes.Object_338_1.geometry} material={materials["Material.037"]} />
        <mesh geometry={nodes.Object_338_2.geometry} material={materials["Material.040"]} />
        <mesh geometry={nodes.Object_338_3.geometry} material={materials["Material.043"]} />
      </group>
    </group>
  );
};

const GPU = ({ nodes, materials, started, setMenuId, controlOpacity, selectedComp, compKey }) => {
  const meshRef = useRef(null);

  useEffect(() => {
    if (started) {
      controlOpacity(meshRef.current, compKey);
    }
  }, [selectedComp, started]);

  const handlePointerOver = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("yellow");
        c.material.emissiveIntensity = 0.1;
      });
    }
  };

  const handlePointerOut = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("black");
        c.material.emissiveIntensity = 0;
      });
    }
  };

  const handleClick = (e) => {
    e.stopPropagation();
    setMenuId(compKey);
  };

  return (
    <group
      position={[8.694, -0.546, -0.282]}
      rotation={[-Math.PI, 0, 0]}
      scale={[0.34, 0.006, 1.109]}
      ref={meshRef}
      onPointerOver={started ? handlePointerOver : undefined}
      onPointerOut={started ? handlePointerOut : undefined}
      onClick={started ? handleClick : undefined}
    >
      <mesh geometry={nodes.Object_29.geometry} material={materials["Material.057"]} />
      <mesh geometry={nodes.Object_29_1.geometry} material={materials["Material.066"]} />
      <mesh geometry={nodes.Object_29_2.geometry} material={materials["Material.069"]} />
      <mesh geometry={nodes.Object_29_3.geometry} material={materials["Material.070"]} />
      <mesh geometry={nodes.Object_29_4.geometry} material={materials["Material.072"]} />
      <mesh geometry={nodes.Object_29_5.geometry} material={materials["Material.073"]} />
      <mesh geometry={nodes.Object_29_6.geometry} material={materials["Material.074"]} />
      <mesh geometry={nodes.Object_29_7.geometry} material={materials["Material.075"]} />
      <mesh geometry={nodes.Object_29_8.geometry} material={materials["Material.071"]} />
      <mesh geometry={nodes.Object_29_9.geometry} material={materials["Material.068"]} />
      <mesh geometry={nodes.Object_29_10.geometry} material={materials["Material.067"]} />
      <mesh geometry={nodes.Object_29_11.geometry} material={materials["Material.061"]} />
      <mesh geometry={nodes.Object_29_12.geometry} material={materials["Material.093"]} />
      <mesh geometry={nodes.Object_29_13.geometry} material={materials["Material.064"]} />
      <mesh geometry={nodes.Object_29_14.geometry} material={materials["Material.079"]} />
      <mesh geometry={nodes.Object_29_15.geometry} material={materials["Material.065"]} />
      <mesh geometry={nodes.Object_29_16.geometry} material={materials["Material.078"]} />
      <mesh geometry={nodes.Object_29_17.geometry} material={materials["Material.096"]} />
      <mesh geometry={nodes.Object_29_18.geometry} material={materials["Material.095"]} />
      <mesh geometry={nodes.Object_29_19.geometry} material={materials["Material.001"]} />
      <mesh geometry={nodes.Object_29_20.geometry} material={materials["Material.062"]} />
      <mesh geometry={nodes.Object_29_21.geometry} material={materials["Material.076"]} />
      <mesh geometry={nodes.Object_29_22.geometry} material={materials["Material.077"]} />
      <mesh geometry={nodes.Object_29_23.geometry} material={materials["Material.080"]} />
      <mesh geometry={nodes.Object_29_24.geometry} material={materials["Material.081"]} />
      <mesh geometry={nodes.Object_29_25.geometry} material={materials["Material.082"]} />
      <mesh geometry={nodes.Object_29_26.geometry} material={materials["Material.083"]} />
      <mesh geometry={nodes.Object_29_27.geometry} material={materials["Material.084"]} />
      <mesh geometry={nodes.Object_29_28.geometry} material={materials["Material.085"]} />
      <mesh geometry={nodes.Object_29_29.geometry} material={materials["Material.086"]} />
      <mesh geometry={nodes.Object_29_30.geometry} material={materials["Material.088"]} />
      <mesh geometry={nodes.Object_29_31.geometry} material={materials["Material.090"]} />
      <mesh geometry={nodes.Object_29_32.geometry} material={materials["Material.091"]} />
      <mesh geometry={nodes.Object_29_33.geometry} material={materials["Material.092"]} />
    </group>
  );
};

const Motherboard = ({
  nodes,
  materials,
  started,
  setMenuId,
  controlOpacity,
  selectedComp,
  compKey,
}) => {
  const meshRef = useRef(null);

  useEffect(() => {
    if (started) {
      controlOpacity(meshRef.current, compKey);
    }
  }, [selectedComp, started]);

  const handlePointerOver = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("yellow");
        c.material.emissiveIntensity = 0.1;
      });
    }
  };

  const handlePointerOut = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("black");
        c.material.emissiveIntensity = 0;
      });
    }
  };

  const handleClick = (e) => {
    e.stopPropagation();
    setMenuId(compKey);
  };

  return (
    <group
      position={[9.406, 0.483, -0.44]}
      ref={meshRef}
      onPointerOver={started ? handlePointerOver : undefined}
      onPointerOut={started ? handlePointerOut : undefined}
      onClick={started ? handleClick : undefined}
    >
      <mesh geometry={nodes.Object_54.geometry} material={materials["Material.008"]} />
      <mesh geometry={nodes.Object_54_1.geometry} material={materials["Material.025"]} />
      <mesh geometry={nodes.Object_54_2.geometry} material={materials["Material.027"]} />
      <mesh geometry={nodes.Object_54_3.geometry} material={materials["Material.033"]} />
      <mesh geometry={nodes.Object_54_4.geometry} material={materials["Material.032"]} />
      <mesh geometry={nodes.Object_54_5.geometry} material={materials["Material.072"]} />
      <mesh geometry={nodes.Object_54_6.geometry} material={materials["Material.079"]} />
      <mesh geometry={nodes.Object_54_7.geometry} material={materials["Material.009"]} />
      <mesh geometry={nodes.Object_54_8.geometry} material={materials["Material.010"]} />
      <mesh geometry={nodes.Object_54_9.geometry} material={materials["Material.011"]} />
      <mesh geometry={nodes.Object_54_10.geometry} material={materials["Material.012"]} />
      <mesh geometry={nodes.Object_54_11.geometry} material={materials["Material.013"]} />
      <mesh geometry={nodes.Object_54_12.geometry} material={materials["Material.014"]} />
      <mesh geometry={nodes.Object_54_13.geometry} material={materials["Material.015"]} />
      <mesh geometry={nodes.Object_54_14.geometry} material={materials["Material.016"]} />
      <mesh geometry={nodes.Object_54_15.geometry} material={materials.ROGTRANSPARENT} />
      <mesh geometry={nodes.Object_54_16.geometry} material={materials["Material.017"]} />
      <mesh geometry={nodes.Object_54_17.geometry} material={materials["Material.018"]} />
      <mesh geometry={nodes.Object_54_18.geometry} material={materials["Material.020"]} />
      <mesh geometry={nodes.Object_54_19.geometry} material={materials["Material.019"]} />
      <mesh geometry={nodes.Object_54_20.geometry} material={materials["Material.021"]} />
      <mesh geometry={nodes.Object_54_21.geometry} material={materials["Material.022"]} />
      <mesh geometry={nodes.Object_54_22.geometry} material={materials["Material.023"]} />
      <mesh geometry={nodes.Object_54_23.geometry} material={materials["Material.031"]} />
      <mesh geometry={nodes.Object_54_24.geometry} material={materials["Material.024"]} />
      <mesh geometry={nodes.Object_54_25.geometry} material={materials["Material.030"]} />
      <mesh geometry={nodes.Object_54_26.geometry} material={materials["Material.034"]} />
      <mesh geometry={nodes.Object_54_27.geometry} material={materials["Material.035"]} />
      <mesh geometry={nodes.Object_54_28.geometry} material={materials["Material.026"]} />
      <mesh geometry={nodes.Object_54_29.geometry} material={materials["Material.050"]} />
    </group>
  );
};

const PSU = ({ nodes, materials, started, setMenuId, controlOpacity, selectedComp, compKey }) => {
  const meshRef = useRef(null);

  useEffect(() => {
    if (started) {
      controlOpacity(meshRef.current, compKey);
    }
  }, [selectedComp, started]);

  const handlePointerOver = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("yellow");
        c.material.emissiveIntensity = 0.1;
      });
    }
  };

  const handlePointerOut = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((c) => {
        c.material.emissive.set("black");
        c.material.emissiveIntensity = 0;
      });
    }
  };

  const handleClick = (e) => {
    e.stopPropagation();
    setMenuId(compKey);
  };

  return (
    <group
      position={[8.605, -2.155, -0.667]}
      scale={[0.913, 1, 1]}
      ref={meshRef}
      onPointerOver={started ? handlePointerOver : undefined}
      onPointerOut={started ? handlePointerOut : undefined}
      onClick={started ? handleClick : undefined}
    >
      <mesh geometry={nodes.Object_158.geometry} material={materials["Material.028"]} />
      <mesh geometry={nodes.Object_158_1.geometry} material={materials["Material.029"]} />
      <mesh geometry={nodes.Object_158_2.geometry} material={materials["Material.055"]} />
    </group>
  );
};

const RAMS = ({ nodes, materials, started, setMenuId, controlOpacity, selectedComp, compKey }) => {
  const meshRef = useRef(null);

  const amountOfModules = selectedComp[compKey]?.amountOfModules;

  useEffect(() => {
    if (started) {
      controlOpacity(meshRef.current, compKey);
    }
  }, [selectedComp, started]);

  const handlePointerOver = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((group) => {
        group.children.forEach((mesh) => {
          mesh.material.emissive.set("yellow");
          mesh.material.emissiveIntensity = 0.1;
        });
      });
    }
  };

  const handlePointerOut = (e) => {
    if (meshRef.current) {
      e.stopPropagation();
      meshRef.current.children.forEach((group) => {
        group.children.forEach((mesh) => {
          mesh.material.emissive.set("black");
          mesh.material.emissiveIntensity = 0;
        });
      });
    }
  };

  const handleClick = (e) => {
    e.stopPropagation();
    setMenuId(compKey);
  };

  return (
    <group
      ref={meshRef}
      onPointerOver={started ? handlePointerOver : undefined}
      onPointerOut={started ? handlePointerOut : undefined}
      onClick={started ? handleClick : undefined}
    >
      <group
        position={[9.184, 0.612, 0.694]}
        scale={
          selectedComp[compKey] === null
            ? [0.136, 0.638, 0.023]
            : amountOfModules >= 1
            ? [0.136, 0.638, 0.023]
            : [0, 0, 0]
        }
      >
        <mesh geometry={nodes.Object_297.geometry} material={materials["Material.044"]} />
        <mesh geometry={nodes.Object_297_1.geometry} material={materials["Material.048"]} />
        <mesh geometry={nodes.Object_297_2.geometry} material={materials["Material.046"]} />
        <mesh geometry={nodes.Object_297_3.geometry} material={materials["Material.049"]} />
        <mesh geometry={nodes.Object_297_4.geometry} material={materials["Material.047"]} />
        <mesh geometry={nodes.Object_297_5.geometry} material={materials["Material.045"]} />
      </group>

      <group
        position={[9.184, 0.612, 0.504]}
        scale={
          selectedComp[compKey] === null
            ? [0.136, 0.638, 0.023]
            : amountOfModules >= 2
            ? [0.136, 0.638, 0.023]
            : [0, 0, 0]
        }
      >
        <mesh geometry={nodes.Object_317.geometry} material={materials["Material.044"]} />
        <mesh geometry={nodes.Object_317_1.geometry} material={materials["Material.047"]} />
        <mesh geometry={nodes.Object_317_2.geometry} material={materials["Material.046"]} />
        <mesh geometry={nodes.Object_317_3.geometry} material={materials["Material.048"]} />
        <mesh geometry={nodes.Object_317_4.geometry} material={materials["Material.045"]} />
        <mesh geometry={nodes.Object_317_5.geometry} material={materials["Material.049"]} />
      </group>

      <group
        position={[9.113, 0.618, 0.632]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={
          selectedComp[compKey] === null
            ? [0.166, 0.637, 0.005]
            : amountOfModules >= 3
            ? [0.166, 0.637, 0.005]
            : [0, 0, 0]
        }
      >
        <mesh geometry={nodes.Object_312.geometry} material={materials["Material.048"]} />
        <mesh geometry={nodes.Object_312_1.geometry} material={materials["Material.049"]} />
        <mesh geometry={nodes.Object_312_2.geometry} material={materials["Material.047"]} />
        <mesh geometry={nodes.Object_312_3.geometry} material={materials["Material.044"]} />
        <mesh geometry={nodes.Object_312_4.geometry} material={materials["Material.046"]} />
        <mesh geometry={nodes.Object_312_5.geometry} material={materials["Material.045"]} />
      </group>

      <group
        position={[9.184, 0.612, 0.406]}
        scale={
          selectedComp[compKey] === null
            ? [0.136, 0.638, 0.023]
            : amountOfModules >= 4
            ? [0.136, 0.638, 0.023]
            : [0, 0, 0]
        }
      >
        <mesh geometry={nodes.Object_327.geometry} material={materials["Material.044"]} />
        <mesh geometry={nodes.Object_327_1.geometry} material={materials["Material.049"]} />
        <mesh geometry={nodes.Object_327_2.geometry} material={materials["Material.047"]} />
        <mesh geometry={nodes.Object_327_3.geometry} material={materials["Material.046"]} />
        <mesh geometry={nodes.Object_327_4.geometry} material={materials["Material.048"]} />
        <mesh geometry={nodes.Object_327_5.geometry} material={materials["Material.045"]} />
      </group>
    </group>
  );
};

export function Model(props) {
  const { nodes, materials } = useGLTF("/PC.glb");
  const { setMenuId, selectedComps, showFullMenu } = useCompContext();

  const controlOpacity = (groupRef, key) => {
    groupRef.traverse((child) => {
      if (child.isMesh) {
        child.material.transparent = true;
        child.material.opacity = selectedComps[key] === null ? 0.5 : 1;
      }
    });
  };

  return (
    <group {...props} dispose={null}>
      <Sidepanel nodes={nodes} materials={materials} started={props.started} />
      <Case nodes={nodes} materials={materials} />
      <Motherboard
        nodes={nodes}
        materials={materials}
        started={props.started && showFullMenu}
        setMenuId={setMenuId}
        controlOpacity={controlOpacity}
        selectedComp={selectedComps}
        compKey={"mobo"}
      />
      <RAMS
        nodes={nodes}
        materials={materials}
        started={props.started && showFullMenu}
        setMenuId={setMenuId}
        controlOpacity={controlOpacity}
        selectedComp={selectedComps}
        compKey={"ram"}
      />
      <GPU
        nodes={nodes}
        materials={materials}
        started={props.started && showFullMenu}
        setMenuId={setMenuId}
        controlOpacity={controlOpacity}
        selectedComp={selectedComps}
        compKey={"gpu"}
      />
      <GPUCable nodes={nodes} materials={materials} />
      <PSU
        nodes={nodes}
        materials={materials}
        started={props.started && showFullMenu}
        setMenuId={setMenuId}
        controlOpacity={controlOpacity}
        selectedComp={selectedComps}
        compKey={"psu"}
      />
      <CPU
        nodes={nodes}
        materials={materials}
        started={props.started && showFullMenu}
        setMenuId={setMenuId}
        controlOpacity={controlOpacity}
        selectedComp={selectedComps}
        compKey={"cpu"}
      />
      <HDD nodes={nodes} materials={materials} />
    </group>
  );
}

useGLTF.preload("/PC.glb");
